from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import smtplib

auth = Blueprint('auth', __name__)

def send_login_credentials(email, full_name, unique_id):
    smtp_server = 'smtp.gmail.com'
    smtp_port = 465
    smtp_username = 'noreply.autogeneratedAWA@gmail.com'
    smtp_password = 'bsuf uzsi vjru jbaf'
    
    magic_link = f"{request.host_url}login/{unique_id}"

    subject = 'Ihre Anmeldedaten'
    body = f'''
    Hallo {full_name},

    Ihr Konto wurde erfolgreich erstellt. Hier sind Ihre Anmeldedaten:
    Eindeutige ID: {unique_id}
    
    Sie koennen sich ueber den unten stehenden Link in Ihr Konto einloggen:
    {magic_link}

    Bitte bewahren Sie diese ID sicher auf, da Sie sie zum Einloggen in Ihr Konto erfordern.
    '''

    message = f'Subject: {subject}\n\n{body}'

    try:
        with smtplib.SMTP_SSL(smtp_server, smtp_port) as smtp:
            smtp.login(smtp_username, smtp_password)
            smtp.sendmail(smtp_username, email, message)
    except Exception as e:
        print(f"Error sending email: {e}")
        
        
@auth.route('/login/<token>', methods=['GET'])
def login_with_magic_link(token):
    user = User.query.filter_by(unique_id=token).first()
    if user:
        login_user(user)
        return redirect(url_for('views.home'))
    else:
        flash('Ungültiger oder abgelaufener Anmeldelink.', category='error')
        return redirect(url_for('auth.login'))
                                                                             

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    
    if request.method == 'POST':
        unique_id = request.form.get('unique_id')

        user = User.query.filter_by(unique_id=unique_id).first()
        if user:
            login_user(user)
            return redirect(url_for('views.home'))
        else:
            flash('Ungültiger Name oder eindeutige ID.', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for('views.home'))
    if request.method == 'POST':
        email = request.form.get('email')
        full_name = request.form.get('firstName')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('E-Mail existiert bereits.', category='error')
        elif len(email) < 4:
            flash('E-Mail muss länger als 3 Zeichen sein.', category='error')
        elif len(full_name) < 2:
            flash('Der Vorname muss größer als 1 Zeichen sein.', category='error')
        else:
            new_user = User(email=email, full_name=full_name)
            db.session.add(new_user)
            db.session.commit()

            send_login_credentials(email, full_name, new_user.unique_id)

            flash('Konto erstellt! Bitte prüfen Sie Ihre E-Mail', category='success')
            return redirect(url_for('auth.login'))

    return render_template("sign_up.html", user=current_user)


@auth.route('/logout')
@login_required  
def logout():
    logout_user() 
    return redirect(url_for('auth.login'))